# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # https://nodejs.org/en/about/releases/
        # EoL of node.js v14: 30 Apr 2023
        # node.js v12.22.7: Cannot use "?."
        # Also need to modify "engines" @ package.json
        node-version: [ 14.x, 16.x, 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        #token: ${{ secrets.CODECOV_TOKEN }}
        node-version: ${{ matrix.node-version }}
    - run: npm install
    #- run: npm ci
    #- run: npm run build --if-present
    - run: npm run test

    # https://github.community/t/how-to-implement-an-after-success-action/16919/5
    - name: report-coverage
      if: ${{ success() }}
      run: npm run report-coverage
